# -*- coding: utf-8 -*-
"""beginner-level-tasks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZI9IcC6W6QliUknhexTg0Ur6K7lVsIP2

# Beginner Level Task 1
"""

# Grocery Store Billing System

items = []
total = 0.0

print("Enter items (type 'done' to finish)\n")

while True:
    name = input("Item name: ")
    if name.lower() == "done":
        break

    qty = int(input("Quantity: "))
    price = float(input("Price per item ($): "))

    cost = qty * price
    total += cost
    items.append((name, qty, price, cost))
    print()

# Discount logic
discount = 0
if total > 100:
    discount = 0.10
elif total > 50:
    discount = 0.05

discount_amount = total * discount
final_total = total - discount_amount

# Receipt printing
print("\n" + "=" * 45)
print("         GROCERY STORE RECEIPT")
print("=" * 45)
print(f"{'Item':15}{'Qty':>5}{'Price':>10}{'Total':>10}")
print("-" * 45)

for item in items:
    print(f"{item[0]:15}{item[1]:>5}{item[2]:>10.2f}{item[3]:>10.2f}")

print("-" * 45)
print(f"{'Sub Total':30}${total:>10.2f}")
print(f"{'Discount':30}-${discount_amount:>9.2f}")
print("=" * 45)
print(f"{'Final Amount':30}${final_total:>10.2f}")
print("=" * 45)

"""# Beginner Level Task - 2"""

# Mobile Balance & Package Simulator

current_balance = 10  # starting balance

while True:
    print("\n--- Mobile Menu ---")
    print("1. Check Balance")
    print("2. Recharge")
    print("3. Subscribe Bundle ($5)")
    print("4. Exit")

    choice = input("Choose an option: ")

    if choice == "1":
        print(f"Your current balance is: ${current_balance}")

    elif choice == "2":
        amount = float(input("Enter recharge amount: "))
        if amount > 0:
            current_balance += amount
            print(f"Recharged successfully. New balance: ${current_balance}")
        else:
            print("Invalid recharge amount")

    elif choice == "3":
        package_price = 5
        if current_balance >= package_price:
            current_balance -= package_price
            print("Bundle subscribed successfully!")
            print(f"Remaining balance: ${current_balance}")
        else:
            print("Insufficient balance to subscribe this bundle")

    elif choice == "4":
        print("Exiting program. Goodbye!")
        break

    else:
        print("Invalid option. Try again.")